name: Notebooks

on: push

jobs:

  build-and-test:
    name: notebooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.2.0
        with:
         activate-environment: pystokes
         environment-file: environment.yml
         # auto-activate-base: true
      - name: make-pystokes
        shell: bash -l {0}
        run: |
          conda activate pystokes
          make
          # make nbtest
      - name: testing-notebooks
        shell: bash -l {0}
        run: |
          make nbtest -e path="examples/shortExamples" recursive=False
                # make nbtest
